//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Election_projectFor_me.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralListCandidate
    {
        public int CandidateID { get; set; }
        public string CandidateName { get; set; }
        public Nullable<int> GeneralListingID { get; set; }
        public string listname { get; set; }
        public Nullable<bool> Sucess { get; set; }
    
        public virtual GeneralListing GeneralListing { get; set; }
    }
}
